"""Trocando name por title

Revision ID: f73ca6040252
Revises: 4e639fb6e878
Create Date: 2021-09-06 10:16:01.801712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f73ca6040252'
down_revision = '4e639fb6e878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_index('ix_books_name', table_name='books')
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.drop_column('books', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.create_index('ix_books_name', 'books', ['name'], unique=False)
    op.drop_column('books', 'title')
    # ### end Alembic commands ###
