"""Trocando name por title

Revision ID: 2ca939017eb4
Revises: f73ca6040252
Create Date: 2021-09-07 02:45:37.726921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca939017eb4'
down_revision = 'f73ca6040252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_ibfk_1', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['owner_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_ibfk_1', 'books', 'users', ['owner_user'], ['id'])
    # ### end Alembic commands ###
