"""put a nice message here

Revision ID: c1375a7b6e20
Revises: 86b85f714eb8
Create Date: 2021-09-06 00:15:38.678293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1375a7b6e20'
down_revision = '86b85f714eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
