"""terceira tentativa

Revision ID: 9186071ce042
Revises: c1375a7b6e20
Create Date: 2021-09-06 09:12:35.682739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9186071ce042'
down_revision = 'c1375a7b6e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
